// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Stdlib__Int from "../src/Stdlib__Int.mjs";
import * as Stdlib__Dict from "../src/Stdlib__Dict.mjs";
import * as Stdlib__JSON from "../src/Stdlib__JSON.mjs";
import * as Stdlib__Array from "../src/Stdlib__Array.mjs";
import * as Stdlib__Float from "../src/Stdlib__Float.mjs";
import * as Stdlib__BigInt from "../src/Stdlib__BigInt.mjs";
import * as Stdlib__Option from "../src/Stdlib__Option.mjs";
import * as Stdlib__Promise from "../src/Stdlib__Promise.mjs";
import * as Stdlib__Undefined from "../src/Stdlib__Undefined.mjs";

console.info("");

console.info("Array");

console.info("---");

var array = [
  1,
  2,
  3,
  4
];

console.info(Stdlib__Array.reduce(array.map(function (x) {
              return (x << 1);
            }), 0, (function (a, b) {
            return a + b | 0;
          })));

console.info(typeof array);

console.info("");

console.info("Date");

console.info("---");

var date = new Date(Date.UTC(2020, 11));

console.log(date.toUTCString());

console.info("");

console.info("Dict");

console.info("---");

var dict = {};

dict["foo"] = "bar";

var dict2 = Object.assign({}, dict);

Stdlib__Dict.$$delete(dict2, "foo");

console.log(dict, dict2);

console.info("");

console.info("Error");

console.info("---");

function f(param) {
  var error = new Error("hello");
  var typeError = new TypeError("error");
  var g = function (param) {
    throw error;
  };
  var h = function (param) {
    throw typeError;
  };
  return [
          g,
          h
        ];
}

console.info("");

console.info("Float/Int");

console.info("---");

console.log((10.2).toFixed(2));

console.log((10).toFixed(2));

console.log(Stdlib__Int.fromString(undefined, "0"));

console.log(Stdlib__Float.fromString("0.1"));

console.info("");

console.info("Intl");

console.info("---");

var currencyFormatter = new Intl.NumberFormat("fr-FR", {
      currency: "EUR",
      style: "currency"
    });

console.log(Intl.NumberFormat.supportedLocalesOf([
          "fr-FR",
          "en-US"
        ]));

console.log(currencyFormatter.format(123.23));

console.info("");

console.info("JSON");

console.info("---");

var json = JSON.parse("{\"foo\": \"bar\"}");

var json$1 = Stdlib__JSON.Decode.classify(json);

var tmp;

if (typeof json$1 === "number" || json$1.TAG !== /* Object */3) {
  tmp = undefined;
} else {
  var value = Stdlib__JSON.Decode.classify(json$1._0["foo"]);
  tmp = typeof value === "number" || value.TAG !== /* String */1 ? undefined : value._0;
}

console.log(tmp);

console.info("");

console.info("Map");

console.info("---");

var map = new Map();

map.set(1, 1);

map.set(2, 2);

map.delete(1);

console.log(map);

console.info("");

console.info("Math");

console.info("---");

console.log(Math.ceil(Math.PI / 2.0));

console.info("");

console.info("BigInt");

console.info("---");

console.log(BigInt(1) / BigInt(12.0));

console.info("");

console.info("Object");

console.info("---");

var myObject = {
  foo: "bar"
};

console.log(Object.create(myObject));

console.log(Object.create(myObject, {
          foo: {
            value: "bar"
          }
        }));

console.log(Object.create(null));

console.log(Object.create(null, {
          foo: {
            value: "bar"
          }
        }));

var copy = Object.assign({}, myObject);

var withNewProp = Object.assign(copy, {
      bar: "baz"
    });

console.info("");

console.info("Promise");

console.info("---");

var promise = new Promise((function (resolve, _reject) {
        setTimeout((function (param) {
                resolve(1);
              }), 100);
      }));

Stdlib__Promise.then(Stdlib__Promise.then(Stdlib__Promise.then(promise, (function (x) {
                  return Promise.resolve(x + 1 | 0);
                })), (function (x) {
              return Promise.resolve(x + 2 | 0);
            })), (function (x) {
          console.log(x);
          return Promise.resolve(undefined);
        })).finally(function (param) {
      console.log("Promise finally");
    });

console.info("");

console.info("RegExp");

console.info("---");

var regex = new RegExp("hello(\\w+)");

var string = "helloworld";

console.log(regex.test(string));

var result = regex.exec(string);

var result$1 = (result == null) ? undefined : Caml_option.some(result);

console.log(Stdlib__Option.map(result$1, (function (prim) {
            return prim.input;
          })));

console.log(Stdlib__Option.map(result$1, (function (prim) {
            return prim.index;
          })));

console.log(Stdlib__Option.map(result$1, (function (prim) {
            return prim.slice(1);
          })));

console.info("");

console.info("Set");

console.info("---");

var set = new Set();

set.add(1).add(2).delete(2);

console.log(set);

console.info("");

console.info("String");

console.info("---");

var regexp = new RegExp("(hello )(world)");

console.log("   Hello world  ".toLowerCase().trim().replace(regexp, (function (param, group1, group2, param$1, param$2) {
            return group1 + group2.toUpperCase();
          })));

console.info("");

console.info("Symbol");

console.info("---");

var x = Symbol.for("Foo");

console.log(x);

var array$1 = Array.from("foo"[Symbol.iterator](undefined));

console.log(array$1);

console.info("");

console.info("Global namespace");

console.info("---");

console.log("number");

var timeout = setTimeout((function (param) {
        console.log("Hello!");
      }), 100);

clearTimeout(timeout);

if (globalThis.hello !== undefined) {
  console.log(globalThis.hello.bar);
  console.log("hello");
}

var resolvedOptions = new Intl.DateTimeFormat().resolvedOptions();

var timeZone = resolvedOptions.timeZone;

var x$1 = Stdlib__Undefined.fromOption(1);

var z = 1.2 % 1.4;

var intFromBigInt = Stdlib__BigInt.toInt(BigInt("10000000000"));

console.log({
      bar: "1"
    });

var Bugfix = {};

console.log(Stdlib__Int.fromString(undefined, "1231231"));

console.log(Stdlib__Int.fromString(undefined, "12.22"));

console.log(Stdlib__Int.fromString(undefined, "99999999999999999"));

console.log(Stdlib__Int.fromString(undefined, "99999999999999999"));

console.log(Stdlib__Int.fromString(2, "010101"));

export {
  date ,
  dict ,
  dict2 ,
  f ,
  currencyFormatter ,
  json ,
  map ,
  myObject ,
  copy ,
  withNewProp ,
  promise ,
  regex ,
  string ,
  result$1 as result,
  set ,
  regexp ,
  array$1 as array,
  timeout ,
  resolvedOptions ,
  timeZone ,
  x$1 as x,
  z ,
  intFromBigInt ,
  Bugfix ,
}
/*  Not a pure module */
